### ISSUE TITLE
Which program did you use to convert DDS to PNG?

### ISSUE THREAD

**Issue by nullsurfer** [FredHappyface/ZeldaTwilightPrincess720p#1]
Sorry I have to open an issue, don't know how to contact you lol. I want to use the original 1080p textures by Henriko, but they are in DDS format.

**Comment by FredHappyface** [comment]
Opening an issue is the perfect way to contact me here so no worries!

I used https://forums.dolphin-emu.org/Thread-custom-texture-tool-ps-v46-2. It's pretty good but can take a while 

Hope that helps

**Comment by nullsurfer** [comment]
Thanks! The tool looks neat
